Fix a potential unicode issue, but can't repro it
I first noticed the errors when I sent this message to jorgeo:
	/topic woo unplanned downtime!
There errors looked like this, but it's unclear what was causing them:

2012-08-28 20:37:14,902 leaf1   ERROR    'utf8' codec can't decode byte 0xb5 in position 109: invalid start byte
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sleekxmpp-1.1.7-py2.6.egg/sleekxmpp/xmlstream/xmlstream.py", line 1620, in _event_runner
    func(*args)
  File "/home/ec2-user/vine-xmpp/leaf_component.py", line 285, in handle_msg
    self.broadcast_msg(msg, bot.participants, sender=msg['from'].user)
  File "/home/ec2-user/vine-xmpp/leaf_component.py", line 540, in broadcast_msg
    self.db_log_message(vinebot_jid.user, sender, body, recipients)
  File "/home/ec2-user/vine-xmpp/leaf_component.py", line 938, in db_log_message
    {'vinebot_id': vinebot_bytes, 'author': author, 'body': body.encode('utf-8'), 'is_whisper': is_whisper})
  File "/home/ec2-user/vine-xmpp/leaf_component.py", line 968, in db_execute
    logging.info('Database OperationalError %s for query, will retry: %s' % (e, query % data))
  File "/usr/lib64/python2.6/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb5 in position 109: invalid start byte