Fail gracefully if ProgrammingError on disconnect
Not sure why I'm getting this error. It seems to have something to do with executing synchronous queries, but I'm not sure how I'd be doing that, so instead I'm going just handle it nicely and dig into MySQL later.

Maybe this has something to do with database queries getting run by the scheduler in send_idle_presences? But since it always seems to happen on disconnect(), I doubt it.

	KeyboardInterrupt
	2013-04-12 04:04:46,916 sleekxmpp.xmlstream.xmlstream INFO    - Waiting for </stream:stream> from server
	2013-04-12 04:04:52,596 leaf00 INFO    - Done
	Exception in thread event_thread_0:
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
	    self.run()
	  File "/usr/lib/python2.7/threading.py", line 504, in run
	    self.__target(*self.__args, **self.__kwargs)
	  File "/home/ubuntu/source_dir/xmpp-env/local/lib/python2.7/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1673, in _event_runner
	    self.disconnect()
	  File "/home/ubuntu/source_dir/xmpp-env/xmpp/leaf_component.py", line 359, in disconnect
	    checked_lock = g.db.is_unlocked_leaf('%s%s' % (constants.leaves_mysql_lock_name, lock_num_to_check))
	  File "/home/ubuntu/source_dir/xmpp-env/xmpp/mysql_conn.py", line 144, in is_unlocked_leaf
	    }, strip_pairs=True)
	  File "/home/ubuntu/source_dir/xmpp-env/xmpp/mysql_conn.py", line 16, in execute_and_fetchall
	    self.execute(query, data)
	  File "/home/ubuntu/source_dir/xmpp-env/xmpp/mysql_conn.py", line 31, in execute
	    self.cursor.execute(query, data)
	  File "/home/ubuntu/source_dir/xmpp-env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 201, in execute
	    self.errorhandler(self, exc, value)
	  File "/home/ubuntu/source_dir/xmpp-env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	ProgrammingError: (2014, "Commands out of sync; you can't run this command now")