Fix bug where vinebots could get more than 2 edges
Most recently, this happened when I was testing Ubuntu, and signed off from both Pidgin and Empathy nearly simultaneously. The test users queen_of_hearts and dormouse were in a conversation with lehrblogger (screenshot http://cl.ly/image/352p1N3h2t3S), and the error looked like this:

	2013-05-22 23:36:11,814 leaf00 INFO    - [idle] 002 participants
	2013-05-22 23:36:11,944 leaf04 INFO    - [offline] 003 participants
	2013-05-22 23:36:11,949 leaf04 INFO    - [remove_participant] 003 participants
	2013-05-22 23:36:12,304 leaf00 INFO    - [idle] 002 participants
	2013-05-22 23:36:12,636 leaf00 INFO    - [idle] 002 participants
	2013-05-22 23:36:13,810 leaf01 INFO    - [offline] 003 participants
	2013-05-22 23:36:13,812 leaf01 INFO    - [remove_participant] 003 participants
	2013-05-22 23:36:23,103 leaf04 WARNING - Failed add_rosteritem XMLRPC command #1 for ravejk with contact_y49v1p1o4m7nyfh4d0rfxc9tc and error [Errno
	 104] Connection reset by peer
	2013-05-22 23:36:23,104 leaf04 WARNING - Failed add_rosteritem XMLRPC command #1 for ravejk with contact_y49v1p1o4m7nyfh4d0rfxc9tc and result None
	2013-05-22 23:36:49,120 leaf01 WARNING - Failed add_rosteritem XMLRPC command #1 for runemadsen with contact_y49v1p1o4m7nyfh4d0rfxc9tc and error [E
	rrno 104] Connection reset by peer
	2013-05-22 23:36:49,121 leaf01 WARNING - Failed add_rosteritem XMLRPC command #1 for runemadsen with contact_y49v1p1o4m7nyfh4d0rfxc9tc and result N
	one
	2013-05-22 23:36:49,122 leaf01 WARNING - Failed add_rosteritem XMLRPC command #1 for christinacaci with contact_y49v1p1o4m7nyfh4d0rfxc9tc and error
	 [Errno 104] Connection reset by peer
	2013-05-22 23:36:49,123 leaf01 WARNING - Failed add_rosteritem XMLRPC command #1 for christinacaci with contact_y49v1p1o4m7nyfh4d0rfxc9tc and resul
	t None
	2013-05-22 23:36:49,124 leaf01 WARNING - Failed add_rosteritem XMLRPC command #1 for kmin with contact_y49v1p1o4m7nyfh4d0rfxc9tc and error [Errno 1
	04] Connection reset by peer
	2013-05-22 23:36:49,125 leaf01 WARNING - Failed add_rosteritem XMLRPC command #1 for kmin with contact_y49v1p1o4m7nyfh4d0rfxc9tc and result None
	2013-05-22 23:36:49,126 leaf01 WARNING - Failed add_rosteritem XMLRPC command #1 for noahjsmith with contact_y49v1p1o4m7nyfh4d0rfxc9tc and error [E
	rrno 104] Connection reset by peer
	2013-05-22 23:36:49,127 leaf01 WARNING - Failed add_rosteritem XMLRPC command #1 for noahjsmith with contact_y49v1p1o4m7nyfh4d0rfxc9tc and result N
	one
	2013-05-22 23:36:49,128 leaf01 WARNING - Failed add_rosteritem XMLRPC command #1 for aac with contact_y49v1p1o4m7nyfh4d0rfxc9tc and error [Errno 10
	4] Connection reset by peer
	2013-05-22 23:36:49,129 leaf01 WARNING - Failed add_rosteritem XMLRPC command #1 for aac with contact_y49v1p1o4m7nyfh4d0rfxc9tc and result None
	2013-05-22 23:36:49,130 leaf01 WARNING - Failed add_rosteritem XMLRPC command #1 for jcn with contact_y49v1p1o4m7nyfh4d0rfxc9tc and error [Errno 10
	4] Connection reset by peer
	2013-05-22 23:36:49,130 leaf01 WARNING - Failed add_rosteritem XMLRPC command #1 for jcn with contact_y49v1p1o4m7nyfh4d0rfxc9tc and result None
	2013-05-22 23:37:27,627 sleekxmpp.xmlstream.xmlstream ERROR   - Error processing event handler: <bound method LeafComponent.handle_msg of <__main__
	.LeafComponent object at 0x284f190>>
	Traceback (most recent call last):
	  File "/home/ubuntu/source_dir/xmpp-env/local/lib/python2.7/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1659, in _event_runner
	    func(*args)
	  File "/home/ubuntu/source_dir/xmpp-env/xmpp/leaf_component.py", line 601, in handle_msg
	    handle_command(msg, user)
	  File "/home/ubuntu/source_dir/xmpp-env/xmpp/leaf_component.py", line 558, in handle_command
	    parent_command_id, response = self.commands.handle_command(sender, msg['body'], vinebot)
	  File "/home/ubuntu/source_dir/xmpp-env/xmpp/slash_commands.py", line 86, in handle_command
	    parent_command_id, result_message = slash_command.execute(sender, arg_string, vinebot)
	  File "/home/ubuntu/source_dir/xmpp-env/xmpp/slash_commands.py", line 48, in execute
	    return self._action(*args)
	  File "/home/ubuntu/source_dir/xmpp-env/xmpp/leaf_component.py", line 1238, in sync_roster
	    errors = []
	  File "/home/ubuntu/source_dir/xmpp-env/xmpp/vinebot.py", line 128, in get_nick
	    users = list(self.edge_users.difference([viewer]))
	  File "/home/ubuntu/source_dir/xmpp-env/xmpp/vinebot.py", line 389, in __getattr__
	    return set([edge1.t_user, edge1.f_user, edge2.t_user, edge2.f_user])
	AttributeError: Vinebot 508 somehow has 4 edges
	2013-05-22 23:39:46,151 sleekxmpp.stanza.rootstanza ERROR   - Error handling {jabber:component:accept}message stanza
	Traceback (most recent call last):
	  File "/home/ubuntu/source_dir/xmpp-env/local/lib/python2.7/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1659, in _event_runner
	    func(*args)
	  File "/home/ubuntu/source_dir/xmpp-env/xmpp/leaf_component.py", line 601, in handle_msg
	    handle_command(msg, user)
	  File "/home/ubuntu/source_dir/xmpp-env/xmpp/leaf_component.py", line 558, in handle_command
	    parent_command_id, response = self.commands.handle_command(sender, msg['body'], vinebot)
	  File "/home/ubuntu/source_dir/xmpp-env/xmpp/slash_commands.py", line 86, in handle_command
	    parent_command_id, result_message = slash_command.execute(sender, arg_string, vinebot)
	  File "/home/ubuntu/source_dir/xmpp-env/xmpp/slash_commands.py", line 48, in execute
	    return self._action(*args)
	  File "/home/ubuntu/source_dir/xmpp-env/xmpp/leaf_component.py", line 1238, in sync_roster
	    errors = []
	  File "/home/ubuntu/source_dir/xmpp-env/xmpp/vinebot.py", line 128, in get_nick
	    users = list(self.edge_users.difference([viewer]))
	  File "/home/ubuntu/source_dir/xmpp-env/xmpp/vinebot.py", line 389, in __getattr__
	    return set([edge1.t_user, edge1.f_user, edge2.t_user, edge2.f_user])
	AttributeError: Vinebot 508 somehow has 4 edges
	2013-05-22 23:39:46,152 sleekxmpp.basexmpp ERROR   - Vinebot 508 somehow has 4 edges
	Traceback (most recent call last):
	  File "/home/ubuntu/source_dir/xmpp-env/local/lib/python2.7/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1659, in _event_runner
	    func(*args)
	  File "/home/ubuntu/source_dir/xmpp-env/xmpp/leaf_component.py", line 601, in handle_msg
	    handle_command(msg, user)
	  File "/home/ubuntu/source_dir/xmpp-env/xmpp/leaf_component.py", line 558, in handle_command
	    parent_command_id, response = self.commands.handle_command(sender, msg['body'], vinebot)
	  File "/home/ubuntu/source_dir/xmpp-env/xmpp/slash_commands.py", line 86, in handle_command
	    parent_command_id, result_message = slash_command.execute(sender, arg_string, vinebot)
	  File "/home/ubuntu/source_dir/xmpp-env/xmpp/slash_commands.py", line 48, in execute
	    return self._action(*args)
	  File "/home/ubuntu/source_dir/xmpp-env/xmpp/leaf_component.py", line 1238, in sync_roster
	    errors = []
	  File "/home/ubuntu/source_dir/xmpp-env/xmpp/vinebot.py", line 128, in get_nick
	    users = list(self.edge_users.difference([viewer]))
	  File "/home/ubuntu/source_dir/xmpp-env/xmpp/vinebot.py", line 389, in __getattr__
	    return set([edge1.t_user, edge1.f_user, edge2.t_user, edge2.f_user])
	AttributeError: Vinebot 508 somehow has 4 edges

Because the state in MySQL looked like this:

	mysql> select * from edges where vinebot_id = 508;
	+-----+---------+-------+------------+---------------------+
	| id  | from_id | to_id | vinebot_id | last_updated_on     |
	+-----+---------+-------+------------+---------------------+
	| 756 |       6 |    16 |        508 | 2013-01-15 10:01:25 |
	| 765 |      19 |    16 |        508 | 2013-01-15 10:01:27 |
	| 805 |      16 |     6 |        508 | 2013-01-15 10:01:37 |
	| 806 |      16 |    19 |        508 | 2013-01-15 10:01:38 |
	+-----+---------+-------+------------+---------------------+
	4 rows in set (0.00 sec)

Subsequent roster sync attempts also failed. It seems like this shouldn't happen, based on how the Vinebot locks are set up, but it did. Regardless, this check should fix it, I think.